create table if not exists public.admins (
    id bigint generated by default as identity primary key,
    username text not null unique,
    password_hash text not null,
    updated_at timestamptz default timezone('utc', now())
);

alter table public.admins enable row level security;
